//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyNSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureMaster
    {
        public int PictureId { get; set; }
        public string PictureName { get; set; }
        public Nullable<int> ProductId { get; set; }
        public byte[] PictureContent { get; set; }
        public string ContentType { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
