//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyNSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public byte[] PictureContent1 { get; set; }
        public string ContentType1 { get; set; }
        public byte[] PictureContent2 { get; set; }
        public string ContentType2 { get; set; }
        public byte[] PictureContent3 { get; set; }
        public string ContentType3 { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
